services:
  - type: web
    name: apisentinel-backend
    runtime: docker
    plan: free
    dockerContext: ./
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APISENTINEL_APP_JWT_SECRET
        sync: false
      - key: APISENTINEL_APP_JWT_EXPIRATION_MS
        value: "86400000"
      - key: APP_ENCRYPTION_SECRET_KEY
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: APISENTINEL_MAIL_CONTACT_TARGET
        sync: false
      - key: APISENTINEL_CORS_ALLOWED_ORIGINS
        value: http://localhost:5173
